#!/usr/bin/env python3
"""
Generate Data/commands.json and Data/commands/*.json for linux-helper.

To add a command: append an entry to COMMANDS below and re-run this script.
  python3 scripts/generate_commands.py

Each entry:
  name, summary, tags, examples[], options[], description, synopsis,
  related[], notes?, aliases?, distros?, distroNotes?, distroVariants?

Basic vs full list:
  BASIC set below marks common commands shown on GET / by default.
  Package managers are never basic; they appear only with ?d=<distro>.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src" / "LinuxHelper" / "Data"
CMD_DIR = DATA / "commands"

# Shown on the default home page (?list=basic). Keep this short and practical.
BASIC: set[str] = {
    "ls", "cd", "pwd", "mkdir", "rm", "cp", "mv", "touch", "find",
    "cat", "less", "head", "tail", "chmod", "chown", "ln",
    "df", "du", "free", "lsblk", "mount", "umount", "fdisk", "blkid", "findmnt",
    "grep", "sed", "sort", "wc", "echo",
    "ps", "top", "kill", "systemctl",
    "ping", "curl", "wget", "ssh", "scp", "rsync", "ip",
    "uname", "whoami", "id", "uptime", "history", "date", "which", "man",
    "sudo", "tar", "zip", "unzip",
    "nano", "vim", "tmux", "crontab",
}

# Preferred one-liner under each command name on compact lists.
PRIMARY_EXAMPLE: dict[str, str] = {
    "ls": "ls -lia",
    "cd": "cd ~",
    "pwd": "pwd",
    "mkdir": "mkdir -p path/to/dir",
    "rm": "rm -rf dirname",
    "cp": "cp -r src/ dest/",
    "mv": "mv old.txt new.txt",
    "touch": "touch file.txt",
    "find": "find . -name '*.log'",
    "cat": "cat file.txt",
    "less": "less file.txt",
    "head": "head -n 20 file.txt",
    "tail": "tail -f /var/log/syslog",
    "chmod": "chmod +x script.sh",
    "chown": "sudo chown user:group file",
    "ln": "ln -s /path/to/target linkname",
    "df": "df -h",
    "du": "du -sh *",
    "free": "free -h",
    "lsblk": "lsblk -f",
    "mount": "mount | head",
    "umount": "sudo umount /mnt",
    "fdisk": "sudo fdisk -l",
    "blkid": "sudo blkid",
    "findmnt": "findmnt",
    "grep": "grep -rn 'pattern' .",
    "sed": "sed 's/foo/bar/g' file",
    "sort": "sort file.txt",
    "wc": "wc -l file.txt",
    "echo": "echo 'hello'",
    "ps": "ps aux",
    "top": "top",
    "kill": "kill PID",
    "systemctl": "systemctl status nginx",
    "ping": "ping -c 4 8.8.8.8",
    "curl": "curl -I https://example.com",
    "wget": "wget https://example.com/file.tgz",
    "ssh": "ssh user@host",
    "scp": "scp file.txt user@host:/tmp/",
    "rsync": "rsync -av src/ dest/",
    "ip": "ip a",
    "uname": "uname -a",
    "whoami": "whoami",
    "id": "id",
    "uptime": "uptime",
    "history": "history | tail",
    "date": "date",
    "which": "which python3",
    "man": "man ls",
    "sudo": "sudo command",
    "tar": "tar -xzf archive.tar.gz",
    "zip": "zip -r archive.zip dir/",
    "unzip": "unzip archive.zip",
    "nano": "nano file.txt",
    "vim": "vim file.txt",
    "tmux": "tmux new -s work",
    "crontab": "crontab -e",
    "apt": "sudo apt update && sudo apt install <pkg>",
    "dnf": "sudo dnf install <pkg>",
    "pacman": "sudo pacman -S <pkg>",
    "apk": "sudo apk add <pkg>",
    "zypper": "sudo zypper install <pkg>",
    "install": "sudo apt install <pkg>",
    "update": "sudo apt update && sudo apt upgrade",
}


def cmd(
    name: str,
    summary: str,
    tags: list[str],
    description: str,
    synopsis: str,
    examples: list[tuple[str, str]],
    options: list[tuple[str, str]] | None = None,
    related: list[str] | None = None,
    notes: str | None = None,
    aliases: list[str] | None = None,
    distros: list[str] | None = None,
    distro_notes: dict[str, str] | None = None,
    distro_variants: dict[str, str] | None = None,
) -> dict:
    return {
        "name": name,
        "summary": summary,
        "tags": tags,
        "description": description,
        "synopsis": synopsis,
        "examples": [{"command": c, "description": d} for c, d in examples],
        "options": [{"flag": f, "description": d} for f, d in (options or [])],
        "related": related or [],
        "notes": notes,
        "aliases": aliases or [],
        "distros": distros or ["all"],
        "distroNotes": distro_notes,
        "distroVariants": distro_variants,
    }


def pick_example(entry: dict) -> str | None:
    name = entry["name"]
    if name in PRIMARY_EXAMPLE:
        return PRIMARY_EXAMPLE[name]
    examples = entry.get("examples") or []
    for ex in examples:
        cmd_text = (ex.get("command") or "").strip()
        if cmd_text and cmd_text != name:
            return cmd_text
    if examples:
        return (examples[0].get("command") or "").strip() or None
    return None


def enrich(entry: dict) -> dict:
    """Mark basic + attach primary example used on compact lists."""
    is_package = "package" in (entry.get("tags") or [])
    entry["basic"] = (entry["name"] in BASIC) and not is_package
    entry["example"] = pick_example(entry)
    return entry


COMMANDS: list[dict] = [
    # ── files & directories ──────────────────────────────────────────────
    cmd(
        "ls",
        "List directory contents",
        ["files", "directory"],
        "List files and directories. One of the most used commands; combine with flags for details, sorting, and hidden files.",
        "ls [OPTION]... [FILE]...",
        [
            ("ls -lia", "Long listing: all files, inode numbers, human details"),
            ("ls -la", "Long listing including hidden files"),
            ("ls -lh", "Human-readable sizes in long format"),
            ("ls -lt", "Sort by modification time (newest first)"),
            ("ls -1", "One entry per line"),
            ("ls /var/log", "List a specific path"),
        ],
        [
            ("-l", "Long format (permissions, owner, size, date)"),
            ("-a", "Show all entries including those starting with ."),
            ("-h", "Human-readable sizes (with -l)"),
            ("-t", "Sort by modification time"),
            ("-r", "Reverse sort order"),
            ("-R", "Recursive"),
            ("-S", "Sort by file size"),
            ("-d", "List directories themselves, not contents"),
        ],
        related=["cd", "pwd", "find", "tree", "stat", "du"],
        aliases=["ll"],
    ),
    cmd(
        "cd",
        "Change the current directory",
        ["files", "directory"],
        "Change the shell's working directory. Paths may be absolute or relative. Special tokens: ~ (home), - (previous), .. (parent).",
        "cd [DIRECTORY]",
        [
            ("cd /var/log", "Go to an absolute path"),
            ("cd ..", "Go up one directory"),
            ("cd ~", "Go to your home directory"),
            ("cd -", "Switch to the previous directory"),
            ("cd ~/projects", "Go to a path under home"),
        ],
        related=["pwd", "ls", "pushd", "popd"],
    ),
    cmd(
        "pwd",
        "Print working directory",
        ["files", "directory"],
        "Print the absolute path of the current working directory.",
        "pwd [-L|-P]",
        [
            ("pwd", "Show current directory"),
        ],
        [
            ("-L", "Logical path (default, follows shell view)"),
            ("-P", "Physical path (resolve symlinks)"),
        ],
        related=["cd", "ls"],
    ),
    cmd(
        "mkdir",
        "Create directories",
        ["files", "directory"],
        "Create one or more directories.",
        "mkdir [OPTION]... DIRECTORY...",
        [
            ("mkdir docs", "Create a single directory"),
            ("mkdir -p a/b/c", "Create nested directories as needed"),
            ("mkdir -m 755 public", "Create with specific permissions"),
        ],
        [
            ("-p", "Create parent directories; no error if exists"),
            ("-m MODE", "Set permission mode"),
            ("-v", "Print a message for each created directory"),
        ],
        related=["rmdir", "rm", "touch", "chmod"],
    ),
    cmd(
        "rmdir",
        "Remove empty directories",
        ["files", "directory"],
        "Remove directories that are empty. Use rm -r for non-empty trees.",
        "rmdir [OPTION]... DIRECTORY...",
        [
            ("rmdir empty_dir", "Remove an empty directory"),
            ("rmdir -p a/b/c", "Remove c, then b, then a if each becomes empty"),
        ],
        [
            ("-p", "Remove DIRECTORY and its empty ancestors"),
        ],
        related=["rm", "mkdir"],
    ),
    cmd(
        "rm",
        "Remove files or directories",
        ["files"],
        "Delete files or directory trees. Irreversible by default — be careful with -r and wildcards, especially as root.",
        "rm [OPTION]... FILE...",
        [
            ("rm file.txt", "Delete a file"),
            ("rm -i *.log", "Prompt before each delete"),
            ("rm -rf build/", "Recursively force-delete a directory (dangerous)"),
            ("rm -v old_*", "Verbose delete matching files"),
        ],
        [
            ("-r, -R", "Recursive (required for directories)"),
            ("-f", "Force; ignore nonexistent files, no prompts"),
            ("-i", "Prompt before every removal"),
            ("-I", "Prompt once before removing more than three files"),
            ("-v", "Explain what is being done"),
        ],
        related=["rmdir", "mv", "trash-put"],
        notes="Prefer trash-cli or desktop trash when available. Never run rm -rf / or unquoted globs as root without checking first.",
    ),
    cmd(
        "cp",
        "Copy files and directories",
        ["files"],
        "Copy files or recursively copy directories.",
        "cp [OPTION]... SOURCE DEST\ncp [OPTION]... SOURCE... DIRECTORY",
        [
            ("cp a.txt b.txt", "Copy a file"),
            ("cp -r src/ backup/", "Copy a directory tree"),
            ("cp -a project/ project.bak/", "Archive mode: preserve attributes, recursive"),
            ("cp -u *.c dest/", "Copy only when source is newer"),
        ],
        [
            ("-r, -R", "Copy directories recursively"),
            ("-a", "Archive mode (-dR --preserve=all)"),
            ("-i", "Prompt before overwrite"),
            ("-u", "Copy only when source is newer than dest"),
            ("-v", "Verbose"),
            ("-p", "Preserve mode, ownership, timestamps"),
        ],
        related=["mv", "rsync", "scp"],
    ),
    cmd(
        "mv",
        "Move or rename files",
        ["files"],
        "Move files/directories or rename them. Same filesystem = rename; otherwise copy+delete.",
        "mv [OPTION]... SOURCE DEST\nmv [OPTION]... SOURCE... DIRECTORY",
        [
            ("mv old.txt new.txt", "Rename a file"),
            ("mv file.txt /tmp/", "Move into a directory"),
            ("mv -i a b", "Prompt before overwriting"),
            ("mv *.log logs/", "Move many files into a folder"),
        ],
        [
            ("-i", "Prompt before overwrite"),
            ("-f", "Do not prompt"),
            ("-n", "Do not overwrite existing"),
            ("-v", "Verbose"),
        ],
        related=["cp", "rename", "rm"],
    ),
    cmd(
        "touch",
        "Create empty file or update timestamps",
        ["files"],
        "Create a file if missing, or update access/modification times.",
        "touch [OPTION]... FILE...",
        [
            ("touch notes.txt", "Create empty file or update mtime"),
            ("touch -c existing", "Do not create if missing"),
            ("touch -t 202401011200 file", "Set a specific timestamp"),
        ],
        [
            ("-c", "Do not create any files"),
            ("-a", "Change access time only"),
            ("-m", "Change modification time only"),
            ("-t STAMP", "Use [[CC]YY]MMDDhhmm[.ss] instead of now"),
        ],
        related=["mkdir", "stat", "date"],
    ),
    cmd(
        "find",
        "Search for files in a directory tree",
        ["files", "search"],
        "Walk a directory hierarchy and select files by name, type, size, time, permissions, and more. Extremely powerful for admin and scripting.",
        "find [PATH...] [EXPRESSION]",
        [
            ("find . -name '*.log'", "Files named *.log under current dir"),
            ("find /var -type d -name cache", "Directories named cache"),
            ("find . -type f -size +100M", "Files larger than 100 MiB"),
            ("find . -mtime -7", "Modified in the last 7 days"),
            ("find . -name '*.tmp' -delete", "Delete matching files"),
            ("find . -type f -exec chmod 644 {} +", "Run chmod on matches"),
        ],
        [
            ("-name PATTERN", "Base name matches shell pattern"),
            ("-iname PATTERN", "Case-insensitive -name"),
            ("-type f|d|l", "File, directory, or symlink"),
            ("-size N", "Size filter (+N larger, -N smaller)"),
            ("-mtime N", "Modified N*24 hours ago"),
            ("-maxdepth N", "Descend at most N levels"),
            ("-exec CMD {} +", "Run command on matches"),
            ("-delete", "Delete matches (GNU find)"),
        ],
        related=["locate", "grep", "fd", "ls"],
    ),
    cmd(
        "locate",
        "Find files by name using a database",
        ["files", "search"],
        "Fast filename search via a prebuilt database (mlocate/plocate). Update DB with updatedb (often via cron).",
        "locate [OPTION]... PATTERN...",
        [
            ("locate passwd", "Find paths containing passwd"),
            ("locate -i readme", "Case-insensitive"),
            ("locate -n 20 '*.conf'", "Limit results"),
        ],
        [
            ("-i", "Case-insensitive"),
            ("-n N", "Limit to N results"),
            ("-e", "Only show existing files"),
            ("-r", "Basic regex"),
        ],
        related=["find", "updatedb", "which"],
        notes="Database may be stale; run sudo updatedb if results look wrong.",
    ),
    cmd(
        "tree",
        "Show directory structure as a tree",
        ["files", "directory"],
        "Display directories and files in a hierarchical tree view. Often needs installing (tree package).",
        "tree [OPTION]... [DIRECTORY]",
        [
            ("tree", "Tree of current directory"),
            ("tree -L 2", "Limit depth to 2 levels"),
            ("tree -d", "Directories only"),
            ("tree -a", "Include hidden files"),
        ],
        [
            ("-L N", "Max display depth"),
            ("-d", "Directories only"),
            ("-a", "All files"),
            ("-h", "Human-readable sizes"),
            ("-I PATTERN", "Exclude pattern"),
        ],
        related=["ls", "find"],
    ),
    cmd(
        "cat",
        "Concatenate and print files",
        ["files", "text"],
        "Write file contents to standard output. Good for small files; use less/more for paging.",
        "cat [OPTION]... [FILE]...",
        [
            ("cat file.txt", "Print a file"),
            ("cat a.txt b.txt", "Concatenate multiple files"),
            ("cat -n file.txt", "Number all output lines"),
            ("cat > file.txt", "Write stdin to file (Ctrl-D to end)"),
            ("cat >> file.txt", "Append stdin to file"),
        ],
        [
            ("-n", "Number output lines"),
            ("-A", "Show non-printing chars (tabs, ends)"),
            ("-s", "Squeeze repeated blank lines"),
        ],
        related=["less", "more", "head", "tail", "tac"],
    ),
    cmd(
        "less",
        "Page through a file or stream",
        ["files", "text"],
        "Interactive pager. Navigate with arrows/PageUp/PageDown, search with /, quit with q.",
        "less [OPTION]... [FILE]...",
        [
            ("less /var/log/syslog", "Page a log file"),
            ("journalctl | less", "Page a long command output"),
            ("less +F logfile", "Follow mode (like tail -f); Ctrl-C then q"),
        ],
        [
            ("-N", "Show line numbers"),
            ("-S", "Chop long lines (no wrap)"),
            ("-i", "Ignore case in searches"),
            ("+F", "Forward forever (follow)"),
        ],
        related=["more", "cat", "tail", "head"],
        notes="Inside less: /pattern search, n next match, g top, G bottom, h help, q quit.",
    ),
    cmd(
        "head",
        "Output the first part of files",
        ["files", "text"],
        "Print the first N lines (default 10) of each file.",
        "head [OPTION]... [FILE]...",
        [
            ("head file.txt", "First 10 lines"),
            ("head -n 20 file.txt", "First 20 lines"),
            ("head -n 5 *.log", "First 5 lines of each matching file"),
        ],
        [
            ("-n N, -N", "Print first N lines"),
            ("-c N", "Print first N bytes"),
            ("-q", "Never print headers with multiple files"),
        ],
        related=["tail", "cat", "less"],
    ),
    cmd(
        "tail",
        "Output the last part of files",
        ["files", "text"],
        "Print the last N lines (default 10). -f follows a growing file (classic for logs).",
        "tail [OPTION]... [FILE]...",
        [
            ("tail file.txt", "Last 10 lines"),
            ("tail -n 50 file.txt", "Last 50 lines"),
            ("tail -f /var/log/syslog", "Follow log in real time"),
            ("tail -n +20 file", "From line 20 to end"),
        ],
        [
            ("-n N", "Last N lines"),
            ("-f", "Follow appended data"),
            ("-F", "Follow and retry if recreated"),
            ("-c N", "Last N bytes"),
        ],
        related=["head", "less", "journalctl"],
    ),
    cmd(
        "chmod",
        "Change file mode bits (permissions)",
        ["files", "permissions", "security"],
        "Change read/write/execute permissions for owner, group, and others. Symbolic (u+x) or octal (755).",
        "chmod [OPTION]... MODE[,MODE]... FILE...\nchmod [OPTION]... OCTAL-MODE FILE...",
        [
            ("chmod +x script.sh", "Make executable for all (who have access)"),
            ("chmod 755 script.sh", "rwxr-xr-x"),
            ("chmod 600 secret.key", "rw------- (owner only)"),
            ("chmod -R u+rwX project/", "Recursive owner read/write/exec on dirs"),
            ("chmod g+w file", "Add group write"),
        ],
        [
            ("-R", "Recursive"),
            ("-v", "Verbose"),
            ("-c", "Report only when a change is made"),
            ("--reference=RFILE", "Copy mode from RFILE"),
        ],
        related=["chown", "chgrp", "umask", "ls", "stat"],
        notes="Octal: owner-group-other; 4=r, 2=w, 1=x. So 7=rwx, 6=rw-, 5=r-x, 4=r--.",
    ),
    cmd(
        "chown",
        "Change file owner and group",
        ["files", "permissions", "user"],
        "Change the user and/or group ownership of files. Usually requires root.",
        "chown [OPTION]... [OWNER][:[GROUP]] FILE...",
        [
            ("sudo chown alice file.txt", "Change owner"),
            ("sudo chown alice:devs file.txt", "Owner and group"),
            ("sudo chown -R www-data:www-data /var/www", "Recursive for web root"),
            ("sudo chown :staff file", "Change group only"),
        ],
        [
            ("-R", "Recursive"),
            ("-v", "Verbose"),
            ("-h", "Affect symlinks instead of referenced file"),
            ("--reference=RFILE", "Copy ownership from RFILE"),
        ],
        related=["chmod", "chgrp", "ls", "id"],
    ),
    cmd(
        "ln",
        "Create hard or symbolic links",
        ["files"],
        "Create hard links or symbolic links (shortcuts) to files or directories.",
        "ln [OPTION]... TARGET LINK_NAME\nln [OPTION]... TARGET... DIRECTORY",
        [
            ("ln -s /usr/bin/python3 py", "Symbolic link"),
            ("ln -s ../config.json .", "Relative symlink"),
            ("ln file.txt hardlink", "Hard link (same inode)"),
            ("ln -sf /new/path link", "Force replace existing symlink"),
        ],
        [
            ("-s", "Make symbolic links instead of hard links"),
            ("-f", "Force; remove existing destination"),
            ("-v", "Verbose"),
            ("-r", "Create symlinks relative to link location (GNU)"),
        ],
        related=["readlink", "ls", "cp"],
        notes="Hard links cannot span filesystems or point at directories (normally). Prefer -s for most uses.",
    ),
    cmd(
        "stat",
        "Display file or filesystem status",
        ["files", "disk"],
        "Show detailed metadata: size, permissions, inode, timestamps, filesystem info.",
        "stat [OPTION]... FILE...",
        [
            ("stat file.txt", "Full status of a file"),
            ("stat -c '%n %s %A' *", "Custom format: name size perms"),
            ("stat -f /", "Filesystem status for /"),
        ],
        [
            ("-c FORMAT", "Custom output format (GNU)"),
            ("-f", "Filesystem status instead of file"),
            ("-L", "Follow symlinks"),
            ("-t", "Terse form"),
        ],
        related=["ls", "df", "du", "file"],
    ),
    cmd(
        "file",
        "Determine file type",
        ["files"],
        "Probe content (magic numbers) to report file type, independent of extension.",
        "file [OPTION]... FILE...",
        [
            ("file document.pdf", "Identify a file"),
            ("file *", "Type of all entries in directory"),
            ("file -i photo.jpg", "MIME type"),
        ],
        [
            ("-i", "Output MIME type strings"),
            ("-b", "Brief (no filename prefix)"),
            ("-L", "Follow symlinks"),
        ],
        related=["stat", "ls", "hexdump"],
    ),
    # ── disk & memory ──────────────────────────────────────────────────
    cmd(
        "df",
        "Report file system disk space usage",
        ["disk", "system"],
        "Show free/used space on mounted filesystems.",
        "df [OPTION]... [FILE]...",
        [
            ("df -h", "Human-readable sizes"),
            ("df -h /", "Space for the filesystem containing /"),
            ("df -i", "Inode usage"),
            ("df -T", "Show filesystem type"),
        ],
        [
            ("-h", "Human-readable (powers of 1024)"),
            ("-H", "Human-readable SI (powers of 1000)"),
            ("-i", "Inode information"),
            ("-T", "Print filesystem type"),
            ("-x TYPE", "Exclude filesystem type"),
        ],
        related=["du", "lsblk", "mount", "stat"],
    ),
    cmd(
        "du",
        "Estimate file space usage",
        ["disk", "files"],
        "Summarize disk usage of files and directories.",
        "du [OPTION]... [FILE]...",
        [
            ("du -sh *", "Size of each item in current dir"),
            ("du -h --max-depth=1", "One level of subdirs"),
            ("du -sh /var/log", "Total size of a path"),
            ("du -ah | sort -h | tail", "Largest items (approx)"),
        ],
        [
            ("-h", "Human-readable"),
            ("-s", "Summarize; total only"),
            ("-a", "All files, not just directories"),
            ("--max-depth=N", "Limit directory depth (GNU)"),
            ("-x", "Skip other filesystems"),
            ("-c", "Grand total"),
        ],
        related=["df", "ncdu", "ls", "find"],
    ),
    cmd(
        "free",
        "Display amount of free and used memory",
        ["memory", "system"],
        "Show RAM and swap usage.",
        "free [OPTION]",
        [
            ("free -h", "Human-readable memory summary"),
            ("free -m", "Show in mebibytes"),
            ("free -s 2", "Refresh every 2 seconds"),
        ],
        [
            ("-h", "Human-readable"),
            ("-b/-k/-m/-g", "Bytes / KiB / MiB / GiB"),
            ("-s N", "Repeat every N seconds"),
            ("-t", "Show total line"),
        ],
        related=["top", "htop", "vmstat", "ps"],
    ),
    cmd(
        "lsblk",
        "List disks, partitions, and mount points",
        ["disk", "system"],
        "List block devices (disks and partitions) as a tree, with sizes and mount points. Best first look at storage layout.",
        "lsblk [OPTION]... [DEVICE]...",
        [
            ("lsblk", "Tree of disks and partitions"),
            ("lsblk -f", "Filesystem type, UUID, and labels"),
            ("lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT", "Common columns for inventory"),
            ("lsblk -p", "Full device paths (/dev/sda1)"),
            ("lsblk -a", "Include empty devices"),
        ],
        [
            ("-f", "Filesystem info (type, label, UUID)"),
            ("-a", "All devices"),
            ("-b", "Bytes instead of human sizes"),
            ("-o LIST", "Output columns"),
            ("-p", "Full device paths"),
            ("-t", "Topology info"),
        ],
        related=["df", "fdisk", "blkid", "findmnt", "mount"],
    ),
    cmd(
        "fdisk",
        "List or edit disk partition tables",
        ["disk", "system"],
        "Manipulate partition tables. Use -l to list partitions on all (or one) disks without entering interactive mode.",
        "fdisk [options] [device]\nfdisk -l [device...]",
        [
            ("sudo fdisk -l", "List partitions on all disks"),
            ("sudo fdisk -l /dev/sda", "List partitions on one disk"),
            ("sudo fdisk /dev/sdb", "Interactive partition editor (careful)"),
        ],
        [
            ("-l", "List partition tables"),
            ("-s", "Print partition size in blocks"),
            ("-w never", "Do not wipe signatures (when scripting)"),
        ],
        related=["lsblk", "parted", "blkid", "cfdisk"],
        notes="Destructive if used interactively without care. Prefer lsblk/fdisk -l for read-only inspection.",
    ),
    cmd(
        "blkid",
        "Print block device attributes (UUID, TYPE, LABEL)",
        ["disk", "system"],
        "Show filesystem type, UUID, and labels for block devices — useful for /etc/fstab entries.",
        "blkid [options] [device...]",
        [
            ("sudo blkid", "List attributes for all known devices"),
            ("sudo blkid /dev/sda1", "Info for one partition"),
            ("blkid -s UUID -o value /dev/sda1", "Print UUID only"),
        ],
        [
            ("-s TAG", "Show only this tag (UUID, TYPE, LABEL)"),
            ("-o FORMAT", "Output format (value, export, ...)"),
            ("-p", "Low-level superblock probe"),
        ],
        related=["lsblk", "findmnt", "fdisk", "mount"],
    ),
    cmd(
        "findmnt",
        "List mounted filesystems in a tree",
        ["disk", "system"],
        "Find and list mounted filesystems (util-linux). Cleaner than raw mount output for inspecting what is mounted where.",
        "findmnt [options]\nfindmnt [options] device|mountpoint",
        [
            ("findmnt", "Tree of all mounts"),
            ("findmnt -t ext4,xfs", "Only certain filesystem types"),
            ("findmnt /", "What is mounted on /"),
            ("findmnt -S /dev/sda1", "Where a device is mounted"),
        ],
        [
            ("-t TYPES", "Limit by filesystem type"),
            ("-S SOURCE", "By source device"),
            ("-T TARGET", "By mount point"),
            ("-o COLS", "Output columns"),
            ("-J", "JSON output"),
        ],
        related=["mount", "lsblk", "df", "blkid"],
    ),
    cmd(
        "mount",
        "Mount a filesystem (or list mounts)",
        ["disk", "system"],
        "Attach a filesystem to a directory tree. With no args, list mounts (findmnt is often clearer).",
        "mount [-t TYPE] [-o OPTIONS] DEVICE DIR\nmount [-l]",
        [
            ("mount", "List mounted filesystems"),
            ("sudo mount /dev/sdb1 /mnt", "Mount a partition"),
            ("sudo mount -o ro /dev/cdrom /media/cd", "Read-only mount"),
            ("sudo mount -t nfs server:/export /mnt", "NFS mount"),
        ],
        [
            ("-t TYPE", "Filesystem type"),
            ("-o OPTIONS", "Mount options (ro, rw, noexec, ...)"),
            ("-a", "Mount all from fstab"),
            ("-l", "List with labels"),
        ],
        related=["umount", "lsblk", "findmnt", "df", "fstab"],
        notes="Persistent mounts belong in /etc/fstab or systemd .mount units.",
    ),
    cmd(
        "umount",
        "Unmount filesystems",
        ["disk", "system"],
        "Detach a mounted filesystem. Fails if busy (open files/cwd on mount).",
        "umount [OPTION]... {DIR|DEVICE}...",
        [
            ("sudo umount /mnt", "Unmount by mount point"),
            ("sudo umount /dev/sdb1", "Unmount by device"),
            ("sudo umount -l /mnt", "Lazy unmount when busy"),
        ],
        [
            ("-l", "Lazy unmount"),
            ("-f", "Force (for unreachable NFS)"),
            ("-a", "Unmount all from fstab/mtab (careful)"),
        ],
        related=["mount", "lsof", "fuser", "lsblk", "findmnt"],
    ),
    # ── text processing ────────────────────────────────────────────────
    cmd(
        "grep",
        "Print lines matching a pattern",
        ["text", "search"],
        "Search input or files for lines matching a regex. Fundamental for logs and code.",
        "grep [OPTION]... PATTERN [FILE]...\ngrep [OPTION]... -e PATTERN ... [FILE]...",
        [
            ("grep error app.log", "Lines containing error"),
            ("grep -i error app.log", "Case-insensitive"),
            ("grep -R --include='*.py' TODO .", "Recursive in Python files"),
            ("grep -n pattern file", "Show line numbers"),
            ("ps aux | grep nginx", "Filter process list"),
            ("grep -v '^#' config", "Exclude comment lines"),
        ],
        [
            ("-i", "Ignore case"),
            ("-n", "Line numbers"),
            ("-r/-R", "Recursive"),
            ("-v", "Invert match"),
            ("-E", "Extended regex (egrep)"),
            ("-F", "Fixed strings (fgrep)"),
            ("-c", "Count matching lines"),
            ("-l", "Only filenames with matches"),
            ("-A/-B/-C N", "Context lines after/before/both"),
        ],
        related=["rg", "awk", "sed", "find", "journalctl"],
    ),
    cmd(
        "sed",
        "Stream editor for filtering and transforming text",
        ["text"],
        "Edit streams non-interactively: substitute, delete, print lines matching patterns.",
        "sed [OPTION]... {script} [FILE]...",
        [
            ("sed 's/foo/bar/' file", "Replace first foo on each line"),
            ("sed 's/foo/bar/g' file", "Replace all foo on each line"),
            ("sed -i 's/foo/bar/g' file", "Edit file in place"),
            ("sed -n '10,20p' file", "Print lines 10–20"),
            ("sed '/^#/d' file", "Delete comment lines"),
        ],
        [
            ("-i", "In-place edit (GNU; use -i.bak for backup)"),
            ("-n", "Suppress automatic printing"),
            ("-E", "Extended regex"),
            ("-e script", "Add script"),
        ],
        related=["awk", "grep", "tr", "cut"],
    ),
    cmd(
        "awk",
        "Pattern scanning and text processing language",
        ["text"],
        "Process text by fields and records. Ideal for columns in logs and CSVs.",
        "awk [OPTION]... 'program' [FILE]...",
        [
            ("awk '{print $1}' file", "Print first field"),
            ("awk -F: '{print $1}' /etc/passwd", "Field separator :"),
            ("awk 'NR==5' file", "Print line 5"),
            ("awk '{sum+=$1} END {print sum}' nums", "Sum first column"),
            ("ps aux | awk '{print $2, $11}'", "PID and command"),
        ],
        [
            ("-F fs", "Field separator"),
            ("-v var=val", "Assign variable"),
            ("-f progfile", "Read program from file"),
        ],
        related=["sed", "cut", "grep", "sort"],
    ),
    cmd(
        "cut",
        "Remove sections from each line",
        ["text"],
        "Select columns/bytes/characters from lines — simple field extraction.",
        "cut OPTION... [FILE]...",
        [
            ("cut -d: -f1 /etc/passwd", "First field, colon-separated"),
            ("cut -c1-10 file", "Characters 1–10"),
            ("echo 'a,b,c' | cut -d, -f2", "Middle CSV field"),
        ],
        [
            ("-d DELIM", "Field delimiter"),
            ("-f LIST", "Select fields"),
            ("-c LIST", "Select characters"),
            ("-b LIST", "Select bytes"),
            ("--complement", "Invert selection (GNU)"),
        ],
        related=["awk", "sed", "paste"],
    ),
    cmd(
        "sort",
        "Sort lines of text files",
        ["text"],
        "Sort lines alphabetically or numerically; can merge and unique.",
        "sort [OPTION]... [FILE]...",
        [
            ("sort file.txt", "Alphabetical sort"),
            ("sort -n numbers.txt", "Numeric sort"),
            ("sort -k2 file", "Sort by second field"),
            ("sort -u file", "Unique lines only"),
            ("du -h | sort -h", "Human-numeric size sort"),
        ],
        [
            ("-n", "Numeric sort"),
            ("-r", "Reverse"),
            ("-k N", "Sort key field N"),
            ("-u", "Unique"),
            ("-h", "Human numeric (2K 1G)"),
            ("-t CHAR", "Field separator"),
        ],
        related=["uniq", "awk", "cut"],
    ),
    cmd(
        "uniq",
        "Report or omit repeated lines",
        ["text"],
        "Filter adjacent duplicate lines. Usually pipe sorted input into uniq.",
        "uniq [OPTION]... [INPUT [OUTPUT]]",
        [
            ("sort file | uniq", "Unique lines"),
            ("sort file | uniq -c", "Count occurrences"),
            ("sort file | uniq -d", "Only duplicated lines"),
        ],
        [
            ("-c", "Prefix count"),
            ("-d", "Only print duplicates"),
            ("-u", "Only print unique lines"),
            ("-i", "Ignore case"),
        ],
        related=["sort", "awk"],
    ),
    cmd(
        "wc",
        "Print newline, word, and byte counts",
        ["text", "files"],
        "Count lines, words, and bytes/characters in files or stdin.",
        "wc [OPTION]... [FILE]...",
        [
            ("wc file.txt", "Lines, words, bytes"),
            ("wc -l file.txt", "Line count only"),
            ("find . -name '*.py' | wc -l", "Count matching paths"),
            ("cat file | wc -w", "Word count from stdin"),
        ],
        [
            ("-l", "Lines"),
            ("-w", "Words"),
            ("-c", "Bytes"),
            ("-m", "Characters"),
            ("-L", "Length of longest line"),
        ],
        related=["cat", "grep", "awk"],
    ),
    cmd(
        "diff",
        "Compare files line by line",
        ["text", "files"],
        "Show differences between two files. Basis for patches.",
        "diff [OPTION]... FILES",
        [
            ("diff a.txt b.txt", "Basic diff"),
            ("diff -u a.txt b.txt", "Unified diff (common for patches)"),
            ("diff -r dir1 dir2", "Recursive directory compare"),
            ("diff -y a b", "Side-by-side"),
        ],
        [
            ("-u", "Unified format"),
            ("-c", "Context format"),
            ("-r", "Recursive"),
            ("-i", "Ignore case"),
            ("-w", "Ignore whitespace"),
            ("-y", "Side by side"),
        ],
        related=["vimdiff", "git", "comm", "cmp"],
    ),
    cmd(
        "tee",
        "Read stdin and write to stdout and files",
        ["text", "files"],
        "Duplicate a pipeline stream to one or more files while still passing it on.",
        "tee [OPTION]... [FILE]...",
        [
            ("command | tee out.txt", "Save output and still see it"),
            ("command | tee -a log.txt", "Append to log"),
            ("echo hi | tee a.txt b.txt", "Write to multiple files"),
        ],
        [
            ("-a", "Append instead of overwrite"),
            ("-i", "Ignore interrupts"),
        ],
        related=["cat", "script"],
    ),
    cmd(
        "echo",
        "Display a line of text",
        ["text", "shell"],
        "Write arguments to standard output. Useful in scripts and for quick prints.",
        "echo [OPTION]... [STRING]...",
        [
            ("echo hello", "Print text"),
            ("echo -n 'no newline'", "Suppress trailing newline"),
            ("echo -e 'line1\\nline2'", "Interpret escapes"),
            ("echo $PATH", "Print a variable"),
        ],
        [
            ("-n", "No trailing newline"),
            ("-e", "Enable backslash escapes"),
            ("-E", "Disable escapes (default bash)"),
        ],
        related=["printf", "cat"],
    ),
    # ── process & service ──────────────────────────────────────────────
    cmd(
        "ps",
        "Report a snapshot of current processes",
        ["process", "system"],
        "List running processes. Common forms: ps aux (BSD) and ps -ef (System V).",
        "ps [OPTION]...",
        [
            ("ps aux", "All processes with details (BSD style)"),
            ("ps -ef", "All processes (System V style)"),
            ("ps -u $USER", "Your processes"),
            ("ps aux | grep nginx", "Find nginx processes"),
            ("ps -p 1234 -o pid,cmd,%mem", "Custom columns for a PID"),
        ],
        [
            ("a", "All users' processes with tty (BSD)"),
            ("u", "User-oriented format (BSD)"),
            ("x", "Processes without controlling tty (BSD)"),
            ("-e", "Every process"),
            ("-f", "Full format"),
            ("-p PID", "Select by PID"),
            ("-o FMT", "User-defined format"),
        ],
        related=["top", "htop", "kill", "pgrep", "systemctl"],
    ),
    cmd(
        "top",
        "Dynamic real-time process view",
        ["process", "memory", "system"],
        "Interactive process monitor sorted by CPU by default. Press q to quit, h for help.",
        "top [OPTION]...",
        [
            ("top", "Interactive process monitor"),
            ("top -u root", "Only root's processes"),
            ("top -p 1234,5678", "Watch specific PIDs"),
            ("top -b -n 1", "Batch mode one snapshot (scripting)"),
        ],
        [
            ("-u USER", "Filter by user"),
            ("-p PID", "Monitor specific PIDs"),
            ("-b", "Batch mode"),
            ("-n N", "Number of iterations"),
            ("-d SEC", "Delay between updates"),
        ],
        related=["htop", "ps", "free", "vmstat"],
        notes="Inside top: P sort CPU, M sort memory, k kill, 1 toggle per-CPU, q quit.",
    ),
    cmd(
        "htop",
        "Interactive process viewer (enhanced)",
        ["process", "memory", "system"],
        "Friendlier alternative to top with colors, mouse, and easier killing/searching. May need install.",
        "htop [OPTION]...",
        [
            ("htop", "Open interactive viewer"),
            ("htop -u deploy", "Only one user's processes"),
            ("htop -p 1234", "Single PID"),
        ],
        [
            ("-u USER", "Show only USER's processes"),
            ("-p PID", "Show only given PIDs"),
            ("-t", "Tree view"),
            ("-d DELAY", "Update delay in tenths of seconds"),
        ],
        related=["top", "ps", "kill"],
    ),
    cmd(
        "kill",
        "Send a signal to a process",
        ["process"],
        "Send signals (default TERM) to PIDs. Use kill -9 only when graceful stop fails.",
        "kill [OPTION]... PID...\nkill -SIGNAL PID...",
        [
            ("kill 1234", "SIGTERM — ask process to exit"),
            ("kill -15 1234", "Same as SIGTERM"),
            ("kill -HUP 1234", "Reload/config hangup (daemons)"),
            ("kill -9 1234", "SIGKILL — force kill (last resort)"),
            ("kill -l", "List signal names"),
        ],
        [
            ("-s SIGNAL", "Signal to send"),
            ("-l", "List signals"),
            ("-9", "SIGKILL"),
            ("-15", "SIGTERM"),
        ],
        related=["killall", "pkill", "pgrep", "ps", "top"],
        notes="Order of politeness: TERM (15) → wait → KILL (9). KILL cannot be caught.",
    ),
    cmd(
        "killall",
        "Kill processes by name",
        ["process"],
        "Send a signal to all processes matching a name.",
        "killall [OPTION]... name...",
        [
            ("killall firefox", "Terminate all firefox processes"),
            ("killall -9 hung-app", "Force kill by name"),
            ("killall -i python", "Interactive confirm"),
        ],
        [
            ("-9", "SIGKILL"),
            ("-i", "Interactive"),
            ("-u USER", "Only USER's processes"),
            ("-v", "Verbose"),
        ],
        related=["kill", "pkill", "pgrep"],
    ),
    cmd(
        "jobs",
        "List active shell jobs",
        ["process", "shell"],
        "Show background/stopped jobs of the current shell session.",
        "jobs [OPTION]... [jobspec]...",
        [
            ("jobs", "List jobs"),
            ("jobs -l", "Include PIDs"),
        ],
        [
            ("-l", "Also list PIDs"),
            ("-p", "PIDs only"),
            ("-r", "Running only"),
            ("-s", "Stopped only"),
        ],
        related=["bg", "fg", "nohup", "disown"],
    ),
    cmd(
        "bg",
        "Resume job in the background",
        ["process", "shell"],
        "Continue a stopped job in the background.",
        "bg [jobspec ...]",
        [
            ("bg", "Resume most recent stopped job in background"),
            ("bg %1", "Resume job 1 in background"),
        ],
        related=["fg", "jobs", "Ctrl-Z"],
        notes="Stop a foreground process with Ctrl-Z, then bg to keep it running.",
    ),
    cmd(
        "fg",
        "Bring job to the foreground",
        ["process", "shell"],
        "Resume a job in the foreground (takes terminal control).",
        "fg [jobspec]",
        [
            ("fg", "Foreground the current/previous job"),
            ("fg %2", "Foreground job 2"),
        ],
        related=["bg", "jobs"],
    ),
    cmd(
        "nohup",
        "Run a command immune to hangups",
        ["process", "shell"],
        "Run a command that keeps running after logout; output defaults to nohup.out.",
        "nohup COMMAND [ARG]...",
        [
            ("nohup ./long-job.sh &", "Background job survives hangup"),
            ("nohup python server.py > server.log 2>&1 &", "With explicit log"),
        ],
        related=["disown", "systemd", "screen", "tmux"],
        notes="For services prefer systemd units over nohup.",
    ),
    cmd(
        "systemctl",
        "Control the systemd system and service manager",
        ["process", "system", "service"],
        "Manage services, targets, and unit state on systemd-based distros (most modern Linux).",
        "systemctl [OPTIONS...] COMMAND [UNIT...]",
        [
            ("systemctl status nginx", "Service status"),
            ("sudo systemctl start nginx", "Start service"),
            ("sudo systemctl stop nginx", "Stop service"),
            ("sudo systemctl restart nginx", "Restart"),
            ("sudo systemctl enable nginx", "Start at boot"),
            ("sudo systemctl disable nginx", "Don't start at boot"),
            ("systemctl list-units --type=service --state=running", "Running services"),
            ("journalctl -u nginx -f", "Follow service logs (related)"),
        ],
        [
            ("status", "Show runtime status"),
            ("start/stop/restart", "Control service lifecycle"),
            ("enable/disable", "Boot persistence"),
            ("reload", "Reload config if supported"),
            ("daemon-reload", "Reload unit files after changes"),
            ("--user", "User session manager"),
            ("--failed", "List failed units"),
        ],
        related=["journalctl", "service", "ps"],
        distro_notes={
            "alpine": "Alpine often uses OpenRC (rc-service) instead of systemd.",
        },
    ),
    cmd(
        "journalctl",
        "Query the systemd journal",
        ["system", "text", "service"],
        "Read logs collected by systemd-journald.",
        "journalctl [OPTIONS...] [MATCHES...]",
        [
            ("journalctl -xe", "Recent logs with explanations"),
            ("journalctl -u ssh -f", "Follow SSH service logs"),
            ("journalctl -b", "Current boot only"),
            ("journalctl --since '1 hour ago'", "Time filter"),
            ("journalctl -p err", "Priority error and above"),
            ("journalctl -n 100", "Last 100 entries"),
        ],
        [
            ("-u UNIT", "Unit/service filter"),
            ("-f", "Follow"),
            ("-b", "Current boot"),
            ("-n N", "Last N lines"),
            ("-p PRI", "Priority threshold"),
            ("--since/--until", "Time range"),
            ("-xe", "End of journal + catalog explanations"),
        ],
        related=["systemctl", "dmesg", "tail"],
    ),
    # ── network ────────────────────────────────────────────────────────
    cmd(
        "ping",
        "Send ICMP ECHO_REQUEST to network hosts",
        ["network"],
        "Test reachability and measure round-trip time to a host.",
        "ping [OPTION]... HOST",
        [
            ("ping 8.8.8.8", "Ping Google DNS"),
            ("ping -c 4 example.com", "Exactly 4 probes"),
            ("ping -i 0.5 host", "Interval 0.5s"),
        ],
        [
            ("-c N", "Stop after N replies"),
            ("-i SEC", "Interval between packets"),
            ("-W SEC", "Timeout waiting for reply"),
            ("-4 / -6", "Force IPv4 / IPv6"),
        ],
        related=["traceroute", "mtr", "ip", "curl"],
    ),
    cmd(
        "curl",
        "Transfer data from or to a server",
        ["network", "web"],
        "Swiss-army knife for HTTP and many other protocols. Great for APIs and debugging.",
        "curl [OPTION]... [URL]...",
        [
            ("curl https://example.com", "GET a URL"),
            ("curl -I https://example.com", "Headers only"),
            ("curl -o file.tgz URL", "Save to file"),
            ("curl -O URL", "Save using remote name"),
            ("curl -X POST -d 'a=1' URL", "POST form data"),
            ("curl -H 'Accept: application/json' URL", "Custom header"),
            ("curl -u user:pass URL", "HTTP basic auth"),
            ("curl -L URL", "Follow redirects"),
        ],
        [
            ("-I", "HEAD / show headers"),
            ("-O", "Remote-name output"),
            ("-o FILE", "Write to FILE"),
            ("-X METHOD", "HTTP method"),
            ("-d DATA", "Request body"),
            ("-H HEADER", "Add header"),
            ("-L", "Follow redirects"),
            ("-f", "Fail on HTTP errors"),
            ("-s", "Silent"),
            ("-v", "Verbose"),
        ],
        related=["wget", "httpie", "ssh"],
    ),
    cmd(
        "wget",
        "Non-interactive network downloader",
        ["network", "web"],
        "Download files over HTTP/HTTPS/FTP. Strong recursive mirroring support.",
        "wget [OPTION]... [URL]...",
        [
            ("wget https://example.com/file.tgz", "Download a file"),
            ("wget -c URL", "Continue partial download"),
            ("wget -O out.bin URL", "Save as out.bin"),
            ("wget -r -np -k site/", "Mirror site (careful)"),
        ],
        [
            ("-c", "Continue"),
            ("-O FILE", "Output document"),
            ("-q", "Quiet"),
            ("-r", "Recursive"),
            ("-np", "No parent"),
            ("--limit-rate=R", "Throttle"),
        ],
        related=["curl", "aria2c"],
    ),
    cmd(
        "ssh",
        "OpenSSH remote login client",
        ["network", "security"],
        "Secure remote shell. Also used for tunnels, file copy backends, and remote commands.",
        "ssh [OPTION]... [user@]hostname [command]",
        [
            ("ssh user@host", "Interactive login"),
            ("ssh -p 2222 user@host", "Custom port"),
            ("ssh user@host 'uptime'", "Run remote command"),
            ("ssh -i ~/.ssh/id_ed25519 user@host", "Specific key"),
            ("ssh -L 8080:localhost:80 user@host", "Local port forward"),
            ("ssh -N -D 1080 user@host", "SOCKS dynamic forward"),
        ],
        [
            ("-p PORT", "Port"),
            ("-i KEY", "Identity file"),
            ("-L", "Local port forward"),
            ("-R", "Remote port forward"),
            ("-D", "Dynamic SOCKS"),
            ("-N", "No remote command"),
            ("-v", "Verbose (debug)"),
            ("-A", "Agent forwarding"),
        ],
        related=["scp", "sftp", "sshd", "ssh-keygen"],
    ),
    cmd(
        "scp",
        "Secure copy (remote file copy over SSH)",
        ["network", "files"],
        "Copy files between hosts using SSH.",
        "scp [OPTION]... SOURCE... DEST",
        [
            ("scp file.txt user@host:/tmp/", "Local → remote"),
            ("scp user@host:/var/log/app.log .", "Remote → local"),
            ("scp -r project/ user@host:~/project", "Recursive directory"),
            ("scp -P 2222 file user@host:", "Custom SSH port (capital P)"),
        ],
        [
            ("-r", "Recursive"),
            ("-P PORT", "SSH port"),
            ("-i KEY", "Identity file"),
            ("-C", "Compression"),
            ("-p", "Preserve times"),
        ],
        related=["rsync", "sftp", "ssh", "cp"],
        notes="For sync/resume/large trees, rsync over SSH is usually better than scp.",
    ),
    cmd(
        "rsync",
        "Fast incremental file transfer",
        ["network", "files"],
        "Efficient copy/sync locally or over SSH. Only transfers differences.",
        "rsync [OPTION]... SRC... [DEST]",
        [
            ("rsync -av src/ dest/", "Archive verbose local sync"),
            ("rsync -avz ./ user@host:backup/", "To remote with compression"),
            ("rsync -av --delete src/ dest/", "Make dest mirror src"),
            ("rsync -avn src/ dest/", "Dry run"),
            ("rsync -av --progress big/ user@host:big/", "Show progress"),
        ],
        [
            ("-a", "Archive (recursive, preserve meta)"),
            ("-v", "Verbose"),
            ("-z", "Compress in transit"),
            ("-n", "Dry run"),
            ("--delete", "Delete extraneous files on dest"),
            ("-P", "Progress + partial"),
            ("-e ssh", "Use SSH (default for remote)"),
        ],
        related=["scp", "cp", "rclone"],
        notes="Trailing slash on src matters: src/ copies contents; src copies the directory.",
    ),
    cmd(
        "ss",
        "Socket statistics (modern netstat)",
        ["network", "system"],
        "Inspect sockets: listening ports, established connections. Preferred over netstat.",
        "ss [OPTION]... [FILTER]",
        [
            ("ss -tulpn", "Listening TCP/UDP with processes"),
            ("ss -s", "Summary statistics"),
            ("ss -tp", "TCP with processes"),
            ("ss dst 1.2.3.4", "Filter by destination"),
        ],
        [
            ("-t", "TCP"),
            ("-u", "UDP"),
            ("-l", "Listening"),
            ("-a", "All"),
            ("-n", "Numeric, no resolve"),
            ("-p", "Show process"),
            ("-s", "Summary"),
        ],
        related=["ip", "netstat", "lsof", "nmap"],
    ),
    cmd(
        "ip",
        "Show / manipulate routing, devices, policy routing",
        ["network", "system"],
        "Modern replacement for ifconfig/route. Part of iproute2.",
        "ip [OPTIONS] OBJECT COMMAND",
        [
            ("ip a", "Show addresses (ip addr)"),
            ("ip link", "Show interfaces"),
            ("ip r", "Show routes"),
            ("ip neigh", "Neighbor/ARP table"),
            ("sudo ip link set eth0 up", "Bring interface up"),
            ("sudo ip addr add 192.168.1.10/24 dev eth0", "Add address"),
        ],
        [
            ("addr / a", "Addresses"),
            ("link", "Network devices"),
            ("route / r", "Routing table"),
            ("neigh", "Neighbor table"),
            ("-br", "Brief output"),
            ("-c", "Color"),
        ],
        related=["ss", "ping", "nmcli", "ifconfig"],
    ),
    cmd(
        "hostname",
        "Show or set the system's host name",
        ["network", "system"],
        "Print the hostname; with privileges can set it (prefer hostnamectl on systemd).",
        "hostname [OPTION]... [NAME]",
        [
            ("hostname", "Print hostname"),
            ("hostname -f", "FQDN if configured"),
            ("hostname -I", "All IP addresses"),
        ],
        [
            ("-f", "FQDN"),
            ("-i", "Addresses for host name"),
            ("-I", "All addresses"),
            ("-s", "Short name"),
        ],
        related=["hostnamectl", "ip", "dnsdomainname"],
    ),
    cmd(
        "dig",
        "DNS lookup utility",
        ["network"],
        "Flexible DNS query tool (bind-utils / dnsutils package).",
        "dig [@server] [OPTIONS] name [type]",
        [
            ("dig example.com", "A record lookup"),
            ("dig example.com MX", "Mail exchangers"),
            ("dig +short example.com", "Brief answer"),
            ("dig @1.1.1.1 example.com", "Query specific resolver"),
            ("dig -x 8.8.8.8", "Reverse lookup"),
        ],
        [
            ("+short", "Terse output"),
            ("+trace", "Trace from root"),
            ("-x ADDR", "Reverse lookup"),
            ("@SERVER", "Nameserver to query"),
        ],
        related=["nslookup", "host", "ping"],
    ),
    # ── system info ────────────────────────────────────────────────────
    cmd(
        "uname",
        "Print system information",
        ["system"],
        "Print kernel name, hostname, kernel release, machine hardware, and more.",
        "uname [OPTION]...",
        [
            ("uname -a", "All information"),
            ("uname -r", "Kernel release"),
            ("uname -m", "Machine architecture"),
            ("uname -s", "Kernel name (Linux)"),
        ],
        [
            ("-a", "All"),
            ("-r", "Kernel release"),
            ("-m", "Machine"),
            ("-n", "Nodename"),
            ("-s", "Kernel name"),
        ],
        related=["hostnamectl", "lsb_release", "cat"],
    ),
    cmd(
        "whoami",
        "Print effective userid",
        ["user", "system"],
        "Print the username associated with the current effective user ID.",
        "whoami",
        [
            ("whoami", "Current effective user"),
            ("sudo whoami", "Usually prints root"),
        ],
        related=["id", "who", "w", "logname"],
    ),
    cmd(
        "id",
        "Print real and effective user/group IDs",
        ["user", "security"],
        "Show uid, gid, and supplementary groups — essential for permission debugging.",
        "id [OPTION]... [USER]",
        [
            ("id", "Your ids and groups"),
            ("id alice", "Info for user alice"),
            ("id -u", "Numeric UID only"),
            ("id -gn", "Primary group name"),
        ],
        [
            ("-u", "User ID only"),
            ("-g", "Primary group ID"),
            ("-G", "All group IDs"),
            ("-n", "Names instead of numbers"),
        ],
        related=["whoami", "groups", "getent"],
    ),
    cmd(
        "uptime",
        "Tell how long the system has been running",
        ["system", "memory"],
        "Show current time, uptime, logged-in users, and load averages (1/5/15 min).",
        "uptime [OPTION]",
        [
            ("uptime", "Classic one-liner"),
            ("uptime -p", "Pretty format"),
            ("uptime -s", "Boot time"),
        ],
        [
            ("-p", "Pretty"),
            ("-s", "Since when"),
        ],
        related=["top", "w", "who", "free"],
    ),
    cmd(
        "lscpu",
        "Display CPU architecture information",
        ["system"],
        "Summarize CPU, cores, threads, caches, virtualization flags from sysfs/proc.",
        "lscpu [OPTION]",
        [
            ("lscpu", "CPU overview"),
            ("lscpu -e", "Extended per-CPU table"),
            ("lscpu -J", "JSON output"),
        ],
        [
            ("-e", "Extended mode"),
            ("-J", "JSON"),
            ("-p", "Parseable"),
        ],
        related=["nproc", "cat", "lshw"],
    ),
    cmd(
        "dmesg",
        "Print or control the kernel ring buffer",
        ["system"],
        "Kernel messages: hardware, drivers, OOM, boot issues.",
        "dmesg [OPTION]...",
        [
            ("dmesg -T", "Human-readable timestamps"),
            ("dmesg -w", "Follow new messages"),
            ("dmesg -l err,warn", "Errors and warnings"),
            ("dmesg | grep -i usb", "Filter USB messages"),
        ],
        [
            ("-T", "Human timestamps"),
            ("-H", "Human-readable pager-friendly"),
            ("-w", "Follow"),
            ("-l LIST", "Level filter"),
            ("-k", "Kernel messages"),
        ],
        related=["journalctl", "lsusb", "lspci"],
    ),
    cmd(
        "history",
        "Display or manipulate the shell history list",
        ["shell"],
        "Show previously entered commands (bash/zsh). Useful with !n and Ctrl-R.",
        "history [OPTION]... [n]",
        [
            ("history", "List history"),
            ("history 20", "Last 20 entries"),
            ("history -c", "Clear history (session)"),
            ("!42", "Re-run history event 42 (bash)"),
            ("Ctrl-R", "Incremental reverse search (readline)"),
        ],
        related=["alias", "which"],
        notes="History file is often ~/.bash_history or ~/.zsh_history.",
    ),
    cmd(
        "date",
        "Print or set the system date and time",
        ["system"],
        "Display current time in many formats; setting the clock needs root (prefer timedatectl).",
        "date [OPTION]... [+FORMAT]",
        [
            ("date", "Current date/time"),
            ("date -u", "UTC"),
            ("date '+%Y-%m-%d %H:%M:%S'", "Custom format"),
            ("date -d 'next Monday'", "Parse a date string (GNU)"),
            ("date -d @1700000000", "From epoch seconds"),
        ],
        [
            ("-u", "UTC"),
            ("-d STRING", "Display time described by STRING (GNU)"),
            ("-s STRING", "Set time (root)"),
            ("+FORMAT", "Output format"),
        ],
        related=["timedatectl", "hwclock", "cal"],
    ),
    cmd(
        "env",
        "Run a program in a modified environment / print env",
        ["shell", "system"],
        "With no args, print environment variables. Can run a command with a modified env.",
        "env [OPTION]... [-] [NAME=VALUE]... [COMMAND [ARG]...]",
        [
            ("env", "Print all environment variables"),
            ("env | grep PATH", "Filter variables"),
            ("env -i HOME=$HOME bash", "Clean environment shell"),
            ("env FOO=bar command", "Run with FOO set"),
        ],
        [
            ("-i", "Start with empty environment"),
            ("-u NAME", "Remove variable"),
            ("-0", "End lines with NUL"),
        ],
        related=["export", "printenv", "set"],
    ),
    cmd(
        "export",
        "Set export attribute for shell variables",
        ["shell"],
        "Mark variables for export to child processes (bash/posix shell builtin).",
        "export [-fn] [name[=value] ...] | -p",
        [
            ("export PATH=\"$PATH:/opt/bin\"", "Prepend to PATH"),
            ("export EDITOR=vim", "Default editor for tools"),
            ("export -p", "List exported variables"),
        ],
        related=["env", "unset", "source"],
        notes="For persistence, add exports to ~/.bashrc, ~/.profile, or /etc/environment.",
    ),
    cmd(
        "which",
        "Locate a command",
        ["shell", "search"],
        "Print the path of executables that would run for a given name (searches PATH).",
        "which [OPTION]... COMMAND...",
        [
            ("which python3", "Where is python3?"),
            ("which -a python", "All matches on PATH"),
        ],
        [
            ("-a", "All matching pathnames"),
        ],
        related=["type", "whereis", "command", "locate"],
        notes="In bash, 'type -a name' is often more accurate (includes builtins/aliases).",
    ),
    cmd(
        "whereis",
        "Locate binary, source, and man page",
        ["shell", "search"],
        "Find the binary, source, and manual pages for a command.",
        "whereis [OPTION]... name...",
        [
            ("whereis ls", "Binary and manpage for ls"),
            ("whereis -b python3", "Binary only"),
        ],
        [
            ("-b", "Search only binaries"),
            ("-m", "Manual pages only"),
            ("-s", "Sources only"),
        ],
        related=["which", "type", "man", "locate"],
    ),
    cmd(
        "man",
        "Interface to the system reference manuals",
        ["shell", "docs"],
        "Read manual pages. Sections: 1 user commands, 2 syscalls, 3 library, 5 file formats, 8 admin.",
        "man [OPTION]... [SECTION] PAGE...",
        [
            ("man ls", "Manual for ls"),
            ("man 5 passwd", "File format for passwd"),
            ("man -k printf", "Search short descriptions (apropos)"),
            ("man -a printf", "All sections named printf"),
        ],
        [
            ("-k KEYWORD", "Search (apropos)"),
            ("-a", "All matching sections"),
            ("-f", "Whatis short description"),
            ("SECTION", "Manual section number"),
        ],
        related=["info", "tldr", "apropos", "whatis"],
        notes="This API exists partly for when man is unavailable — use ?q=<cmd> as a quick refresh.",
    ),
    cmd(
        "sudo",
        "Execute a command as another user",
        ["security", "user", "system"],
        "Run commands with elevated privileges (usually root) per /etc/sudoers policy.",
        "sudo [OPTION]... COMMAND",
        [
            ("sudo apt update", "Run package update as root"),
            ("sudo -i", "Root login shell"),
            ("sudo -u postgres psql", "Run as another user"),
            ("sudo !!", "Re-run last command with sudo (bash)"),
            ("sudo -l", "List allowed commands"),
            ("sudo -E command", "Preserve environment"),
        ],
        [
            ("-i", "Simulate initial login"),
            ("-u USER", "Run as USER"),
            ("-l", "List privileges"),
            ("-E", "Preserve user environment"),
            ("-k", "Invalidate timestamp"),
            ("-s", "Run shell"),
        ],
        related=["su", "doas", "pkexec", "visudo"],
        notes="Prefer least privilege. Edit sudoers with visudo only.",
    ),
    cmd(
        "su",
        "Switch user / become another user",
        ["security", "user"],
        "Start a shell as another user. su - (or su -l) gives a login environment.",
        "su [OPTION]... [-] [USER [ARG]...]",
        [
            ("su -", "Login shell as root (password)"),
            ("su - alice", "Login as alice"),
            ("su -c 'whoami'", "Run one command as root"),
        ],
        [
            ("-, -l", "Login shell"),
            ("-c CMD", "Pass command to the shell"),
            ("-s SHELL", "Shell to use"),
        ],
        related=["sudo", "login"],
        notes="On many desktops, sudo is preferred over su for audited, limited elevation.",
    ),
    # ── archives ───────────────────────────────────────────────────────
    cmd(
        "tar",
        "An archiving utility",
        ["archive", "files"],
        "Create and extract .tar archives, often combined with gzip/bzip2/xz.",
        "tar [OPTION...] [FILE]...",
        [
            ("tar -czf archive.tar.gz dir/", "Create gzip archive"),
            ("tar -xzf archive.tar.gz", "Extract gzip archive"),
            ("tar -tf archive.tar.gz", "List contents"),
            ("tar -xjf archive.tar.bz2", "Extract bzip2"),
            ("tar -cJf archive.tar.xz dir/", "Create xz archive"),
            ("tar -xzf a.tgz -C /target", "Extract into directory"),
        ],
        [
            ("-c", "Create"),
            ("-x", "Extract"),
            ("-t", "List"),
            ("-f FILE", "Archive file"),
            ("-z", "gzip"),
            ("-j", "bzip2"),
            ("-J", "xz"),
            ("-v", "Verbose"),
            ("-C DIR", "Change to DIR"),
            ("-p", "Preserve permissions"),
        ],
        related=["gzip", "zip", "unzip", "zstd"],
        notes="Mnemonic: c=create, x=extract, t=list, f=file, z=gzip. Order of f matters: -f must precede the filename.",
    ),
    cmd(
        "gzip",
        "Compress or expand files (gzip)",
        ["archive", "files"],
        "Compress files with gzip (replaces original with .gz by default).",
        "gzip [OPTION]... [FILE]...",
        [
            ("gzip file.txt", "Compress → file.txt.gz"),
            ("gzip -k file.txt", "Keep original (GNU)"),
            ("gzip -d file.txt.gz", "Decompress"),
            ("gzip -9 big.dat", "Best compression"),
        ],
        [
            ("-d", "Decompress"),
            ("-k", "Keep original"),
            ("-c", "Write to stdout"),
            ("-1 .. -9", "Compression level"),
            ("-t", "Test integrity"),
        ],
        related=["gunzip", "tar", "zcat", "bzip2", "xz"],
    ),
    cmd(
        "zip",
        "Package and compress files",
        ["archive", "files"],
        "Create ZIP archives (common for cross-platform exchange).",
        "zip [OPTION]... zipfile file...",
        [
            ("zip archive.zip file1 file2", "Create zip"),
            ("zip -r project.zip project/", "Recursive directory"),
            ("zip -e secret.zip file", "Encrypt (prompt password)"),
            ("zip -u archive.zip newfile", "Update archive"),
        ],
        [
            ("-r", "Recursive"),
            ("-e", "Encrypt"),
            ("-u", "Update"),
            ("-9", "Best compression"),
            ("-q", "Quiet"),
        ],
        related=["unzip", "tar", "7z"],
    ),
    cmd(
        "unzip",
        "List, test, and extract compressed ZIP files",
        ["archive", "files"],
        "Extract or list ZIP archives.",
        "unzip [OPTION]... file.zip [file...]",
        [
            ("unzip archive.zip", "Extract here"),
            ("unzip archive.zip -d /target", "Extract to directory"),
            ("unzip -l archive.zip", "List contents"),
            ("unzip -o archive.zip", "Overwrite without prompting"),
        ],
        [
            ("-l", "List"),
            ("-d DIR", "Extract into DIR"),
            ("-o", "Overwrite"),
            ("-q", "Quiet"),
            ("-t", "Test"),
        ],
        related=["zip", "tar", "7z"],
    ),
    # ── package managers ───────────────────────────────────────────────
    cmd(
        "apt",
        "APT package manager (Debian/Ubuntu)",
        ["package"],
        "High-level package management for Debian-family systems: install, remove, update, search.",
        "apt [options] command",
        [
            ("sudo apt update", "Refresh package indexes"),
            ("sudo apt upgrade", "Upgrade installed packages"),
            ("sudo apt install nginx", "Install a package"),
            ("sudo apt remove nginx", "Remove package (keep config)"),
            ("sudo apt purge nginx", "Remove package and config"),
            ("apt search keyword", "Search packages"),
            ("apt show nginx", "Package details"),
            ("apt list --upgradable", "What can be upgraded"),
        ],
        [
            ("update", "Resynchronize package index"),
            ("upgrade", "Install newer versions"),
            ("install", "Install packages"),
            ("remove / purge", "Uninstall"),
            ("search / show", "Discover packages"),
            ("autoremove", "Remove unused dependencies"),
        ],
        related=["dpkg", "apt-get", "apt-cache", "snap"],
        distros=["ubuntu", "debian"],
        distro_variants={
            "fedora": "Use: sudo dnf install <pkg>",
            "rhel": "Use: sudo dnf install <pkg>",
            "centos": "Use: sudo dnf install <pkg>",
            "arch": "Use: sudo pacman -S <pkg>",
            "opensuse": "Use: sudo zypper install <pkg>",
            "alpine": "Use: sudo apk add <pkg>",
        },
        notes="Prefer apt over apt-get for interactive use. Always update before upgrade/install.",
    ),
    cmd(
        "dnf",
        "Package manager for Fedora / RHEL family",
        ["package"],
        "DNF (Dandified YUM) installs, updates, and removes RPM packages on Fedora, RHEL, Rocky, Alma.",
        "dnf [options] <command> [<args>...]",
        [
            ("sudo dnf upgrade", "Upgrade packages"),
            ("sudo dnf install nginx", "Install"),
            ("sudo dnf remove nginx", "Remove"),
            ("dnf search keyword", "Search"),
            ("dnf info nginx", "Package info"),
            ("dnf provides /usr/bin/ps", "Which package owns a file"),
            ("sudo dnf autoremove", "Remove unneeded deps"),
        ],
        [
            ("install / remove", "Lifecycle"),
            ("upgrade", "Update packages"),
            ("search / info", "Discovery"),
            ("provides", "Find package by file"),
            ("history", "Transaction history"),
            ("repolist", "Enabled repos"),
        ],
        related=["rpm", "yum"],
        distros=["fedora", "rhel", "centos"],
        aliases=["yum"],
        distro_variants={
            "ubuntu": "Use: sudo apt install <pkg>",
            "debian": "Use: sudo apt install <pkg>",
            "arch": "Use: sudo pacman -S <pkg>",
            "opensuse": "Use: sudo zypper install <pkg>",
            "alpine": "Use: sudo apk add <pkg>",
        },
        notes="yum is often a symlink/alias to dnf on modern Fedora/RHEL.",
    ),
    cmd(
        "pacman",
        "Package manager utility (Arch Linux)",
        ["package"],
        "Arch Linux package manager. Sync (-S), remove (-R), query (-Q), upgrade (-Syu).",
        "pacman <operation> [options] [targets]",
        [
            ("sudo pacman -Syu", "Full system upgrade"),
            ("sudo pacman -S nginx", "Install"),
            ("sudo pacman -Rns nginx", "Remove with deps and config"),
            ("pacman -Ss keyword", "Search sync DBs"),
            ("pacman -Qs keyword", "Search installed"),
            ("pacman -Qi nginx", "Info on installed package"),
            ("pacman -Ql nginx", "List package files"),
            ("sudo pacman -Syyu", "Force refresh then upgrade"),
        ],
        [
            ("-Syu", "Refresh and upgrade"),
            ("-S", "Sync/install"),
            ("-R / -Rns", "Remove (+ deps + config)"),
            ("-Q", "Query local DB"),
            ("-Ss / -Qs", "Search remote / local"),
            ("-Sc", "Clean cache"),
        ],
        related=["yay", "paru", "makepkg"],
        distros=["arch"],
        distro_variants={
            "ubuntu": "Use: sudo apt install <pkg>",
            "debian": "Use: sudo apt install <pkg>",
            "fedora": "Use: sudo dnf install <pkg>",
            "opensuse": "Use: sudo zypper install <pkg>",
            "alpine": "Use: sudo apk add <pkg>",
        },
        notes="AUR helpers (yay/paru) are separate from pacman. Always read pacman output before proceeding.",
    ),
    cmd(
        "apk",
        "Alpine package keeper",
        ["package"],
        "Package manager for Alpine Linux — small, fast, used heavily in containers.",
        "apk [options...] COMMAND [ARGS...]",
        [
            ("sudo apk update", "Refresh indexes"),
            ("sudo apk upgrade", "Upgrade packages"),
            ("sudo apk add nginx", "Install"),
            ("sudo apk del nginx", "Remove"),
            ("apk search keyword", "Search"),
            ("apk info nginx", "Package info"),
            ("apk info -L nginx", "List package contents"),
        ],
        [
            ("update", "Refresh"),
            ("upgrade", "Upgrade"),
            ("add / del", "Install / remove"),
            ("search / info", "Discover"),
            ("cache clean", "Clean cache"),
        ],
        related=["apk-tools"],
        distros=["alpine"],
        distro_variants={
            "ubuntu": "Use: sudo apt install <pkg>",
            "fedora": "Use: sudo dnf install <pkg>",
            "arch": "Use: sudo pacman -S <pkg>",
            "opensuse": "Use: sudo zypper install <pkg>",
        },
    ),
    cmd(
        "zypper",
        "Command line package manager (openSUSE)",
        ["package"],
        "openSUSE / SUSE package manager for RPM packages.",
        "zypper [--global-opts] <command> [--command-opts] [args]",
        [
            ("sudo zypper refresh", "Refresh repos"),
            ("sudo zypper update", "Update packages"),
            ("sudo zypper install nginx", "Install"),
            ("sudo zypper remove nginx", "Remove"),
            ("zypper search keyword", "Search"),
            ("zypper info nginx", "Info"),
        ],
        [
            ("refresh", "Refresh metadata"),
            ("update / dup", "Update / dist-upgrade"),
            ("install / remove", "Lifecycle"),
            ("search / info", "Discovery"),
        ],
        related=["rpm"],
        distros=["opensuse"],
        distro_variants={
            "ubuntu": "Use: sudo apt install <pkg>",
            "fedora": "Use: sudo dnf install <pkg>",
            "arch": "Use: sudo pacman -S <pkg>",
            "alpine": "Use: sudo apk add <pkg>",
        },
    ),
    cmd(
        "install",
        "Distro-aware package install cheat-sheet",
        ["package"],
        "Meta entry: how to install packages on each major distro. Set ?d=<distro> for the matching command.",
        "see distro variants",
        [
            ("sudo apt install <pkg>", "Debian / Ubuntu"),
            ("sudo dnf install <pkg>", "Fedora / RHEL / Rocky / Alma"),
            ("sudo pacman -S <pkg>", "Arch / Manjaro"),
            ("sudo zypper install <pkg>", "openSUSE"),
            ("sudo apk add <pkg>", "Alpine"),
        ],
        related=["apt", "dnf", "pacman", "apk", "zypper", "update"],
        distro_variants={
            "ubuntu": "sudo apt update && sudo apt install <package>",
            "debian": "sudo apt update && sudo apt install <package>",
            "fedora": "sudo dnf install <package>",
            "rhel": "sudo dnf install <package>",
            "centos": "sudo dnf install <package>",
            "arch": "sudo pacman -S <package>",
            "opensuse": "sudo zypper install <package>",
            "alpine": "sudo apk add <package>",
        },
        notes="Pass ?d=ubuntu|fedora|arch|... to highlight your distro's command.",
    ),
    cmd(
        "update",
        "Distro-aware system update cheat-sheet",
        ["package", "system"],
        "Meta entry: refresh indexes and upgrade packages per distro. Use with ?d=<distro>.",
        "see distro variants",
        [
            ("sudo apt update && sudo apt upgrade", "Debian / Ubuntu"),
            ("sudo dnf upgrade", "Fedora / RHEL family"),
            ("sudo pacman -Syu", "Arch"),
            ("sudo zypper refresh && sudo zypper update", "openSUSE"),
            ("sudo apk update && sudo apk upgrade", "Alpine"),
        ],
        related=["install", "apt", "dnf", "pacman"],
        distro_variants={
            "ubuntu": "sudo apt update && sudo apt upgrade",
            "debian": "sudo apt update && sudo apt upgrade",
            "fedora": "sudo dnf upgrade",
            "rhel": "sudo dnf upgrade",
            "centos": "sudo dnf upgrade",
            "arch": "sudo pacman -Syu",
            "opensuse": "sudo zypper refresh && sudo zypper update",
            "alpine": "sudo apk update && sudo apk upgrade",
        },
    ),
    # ── users ──────────────────────────────────────────────────────────
    cmd(
        "useradd",
        "Create a new user or update default user information",
        ["user", "security"],
        "Low-level user creation. Many distros recommend adduser (friendlier) on Debian/Ubuntu.",
        "useradd [OPTIONS] LOGIN",
        [
            ("sudo useradd -m -s /bin/bash alice", "Create user with home and bash"),
            ("sudo passwd alice", "Set password (follow-up)"),
            ("sudo useradd -m -G sudo,docker alice", "With supplementary groups"),
        ],
        [
            ("-m", "Create home directory"),
            ("-s SHELL", "Login shell"),
            ("-G GROUPS", "Supplementary groups"),
            ("-u UID", "Specify UID"),
            ("-d HOME", "Home directory path"),
            ("-c COMMENT", "GECOS field"),
        ],
        related=["userdel", "usermod", "passwd", "adduser"],
        distro_notes={
            "ubuntu": "Prefer: sudo adduser alice (interactive, sets up home/password).",
            "debian": "Prefer: sudo adduser alice.",
        },
    ),
    cmd(
        "userdel",
        "Delete a user account",
        ["user", "security"],
        "Remove a user account from the system.",
        "userdel [OPTIONS] LOGIN",
        [
            ("sudo userdel alice", "Remove user (keep home)"),
            ("sudo userdel -r alice", "Remove user and home directory"),
        ],
        [
            ("-r", "Remove home directory and mail spool"),
            ("-f", "Force removal even if logged in"),
        ],
        related=["useradd", "usermod", "passwd"],
    ),
    cmd(
        "passwd",
        "Change user password",
        ["user", "security"],
        "Set or change passwords. Regular users change their own; root can change any.",
        "passwd [OPTION]... [LOGIN]",
        [
            ("passwd", "Change your password"),
            ("sudo passwd alice", "Set alice's password"),
            ("sudo passwd -l alice", "Lock account"),
            ("sudo passwd -u alice", "Unlock account"),
        ],
        [
            ("-l", "Lock password"),
            ("-u", "Unlock"),
            ("-d", "Delete password (root)"),
            ("-e", "Expire password; force change next login"),
            ("-S", "Status"),
        ],
        related=["useradd", "chpasswd", "chage"],
    ),
    cmd(
        "groups",
        "Print the groups a user is in",
        ["user"],
        "List group memberships for a user.",
        "groups [USERNAME]...",
        [
            ("groups", "Your groups"),
            ("groups alice", "Groups for alice"),
        ],
        related=["id", "getent", "usermod"],
    ),
    # ── misc devops ────────────────────────────────────────────────────
    cmd(
        "crontab",
        "Maintain crontab files for individual users",
        ["system", "process"],
        "Schedule recurring jobs with cron. Each user has a personal crontab.",
        "crontab [-u user] file\ncrontab [-u user] [-l | -r | -e]",
        [
            ("crontab -l", "List your crontab"),
            ("crontab -e", "Edit your crontab"),
            ("crontab -r", "Remove your crontab"),
            ("crontab -l -u alice", "List another user's (root)"),
        ],
        [
            ("-l", "List"),
            ("-e", "Edit"),
            ("-r", "Remove"),
            ("-u USER", "Operate on USER's crontab"),
        ],
        related=["systemctl", "timer", "at"],
        notes="Format: min hour dom month dow command. Example: 0 2 * * * /usr/local/bin/backup.sh",
    ),
    cmd(
        "alias",
        "Define or display aliases",
        ["shell"],
        "Shell builtin to create command shortcuts for the current session.",
        "alias [name[=value] ...]",
        [
            ("alias", "List aliases"),
            ("alias ll='ls -la'", "Create ll alias"),
            ("alias grep='grep --color=auto'", "Colorize grep"),
            ("unalias ll", "Remove alias"),
        ],
        related=["export", "function", "which"],
        notes="Persist aliases in ~/.bashrc or ~/.zshrc.",
    ),
    cmd(
        "source",
        "Execute commands from a file in the current shell",
        ["shell"],
        "Read and execute a file in the current shell (not a subshell). Also written as '.' .",
        "source filename [arguments]\n. filename [arguments]",
        [
            ("source ~/.bashrc", "Reload bash config"),
            (". ./venv/bin/activate", "Activate Python venv"),
            ("source env.sh", "Load environment variables"),
        ],
        related=["export", "bash"],
        aliases=["."],
    ),
    cmd(
        "xargs",
        "Build and execute command lines from standard input",
        ["shell", "text"],
        "Convert stdin items into arguments for another command. Pairs well with find.",
        "xargs [OPTION]... COMMAND [INITIAL-ARGS]...",
        [
            ("find . -name '*.log' | xargs rm", "Delete found files"),
            ("find . -name '*.c' | xargs grep -n TODO", "Grep many files"),
            ("echo 'a b c' | xargs -n 1 echo", "One arg per command"),
            ("cat urls.txt | xargs -n 1 curl -O", "Download each URL"),
            ("find . -print0 | xargs -0 rm", "Safe for spaces/newlines"),
        ],
        [
            ("-n N", "Max args per command"),
            ("-0", "NUL-separated input"),
            ("-P N", "Parallel up to N processes"),
            ("-I {}", "Replace string with input"),
            ("-p", "Prompt before execution"),
        ],
        related=["find", "parallel", "grep"],
    ),
    cmd(
        "watch",
        "Execute a program periodically, showing output fullscreen",
        ["process", "system"],
        "Re-run a command on an interval — handy for monitoring.",
        "watch [OPTION]... COMMAND",
        [
            ("watch -n 1 df -h", "Disk usage every second"),
            ("watch 'ps aux | grep nginx'", "Watch matching processes"),
            ("watch -d free -h", "Highlight differences"),
        ],
        [
            ("-n SEC", "Interval seconds"),
            ("-d", "Highlight differences"),
            ("-t", "No header"),
            ("-e", "Freeze on error"),
        ],
        related=["top", "htop", "while"],
    ),
    cmd(
        "lsof",
        "List open files",
        ["process", "files", "network"],
        "List files opened by processes — includes network sockets. Great for 'device busy' and port checks.",
        "lsof [OPTION]... [FILE]...",
        [
            ("lsof /var/log/syslog", "Who has this file open?"),
            ("sudo lsof -i :80", "Who listens/uses port 80"),
            ("lsof -u alice", "Files opened by alice"),
            ("lsof -p 1234", "Files for PID"),
            ("lsof -iTCP -sTCP:LISTEN", "Listening TCP sockets"),
        ],
        [
            ("-i", "Internet sockets"),
            ("-p PID", "Process"),
            ("-u USER", "User"),
            ("-c CMD", "Command name"),
            ("+D DIR", "Directory recursion"),
        ],
        related=["ss", "fuser", "ps", "netstat"],
    ),
    cmd(
        "tmux",
        "Terminal multiplexer",
        ["shell", "process"],
        "Multiple terminals in one session; detach and reattach later. Essential for remote work.",
        "tmux [command] [flags]",
        [
            ("tmux", "New session"),
            ("tmux new -s work", "Named session"),
            ("tmux ls", "List sessions"),
            ("tmux attach -t work", "Reattach"),
            ("tmux kill-session -t work", "Kill session"),
        ],
        related=["screen", "nohup", "byobu"],
        notes="Default prefix is Ctrl-b. Then: c new window, \" split horiz, % split vert, d detach, arrow switch panes.",
    ),
    cmd(
        "nano",
        "Simple terminal text editor",
        ["files", "text", "shell"],
        "Beginner-friendly editor. Shortcuts shown at the bottom (^ means Ctrl).",
        "nano [OPTION]... [FILE]...",
        [
            ("nano file.txt", "Edit a file"),
            ("nano +10 file.txt", "Open at line 10"),
        ],
        [
            ("Ctrl+O", "Save (Write Out)"),
            ("Ctrl+X", "Exit"),
            ("Ctrl+W", "Search"),
            ("Ctrl+K", "Cut line"),
            ("Ctrl+U", "Paste"),
        ],
        related=["vim", "vi", "emacs", "micro"],
    ),
    cmd(
        "vim",
        "Vi IMproved, a programmer's text editor",
        ["files", "text", "shell"],
        "Modal editor: Normal (navigate), Insert (type), Visual (select), Command-line (:w :q).",
        "vim [OPTION]... [FILE]...",
        [
            ("vim file.txt", "Open file"),
            ("vim +10 file", "Open at line 10"),
            ("vimdiff a b", "Diff two files"),
        ],
        [
            ("i / a / o", "Insert / append / open line"),
            ("Esc", "Back to Normal mode"),
            (":w", "Write/save"),
            (":q", "Quit"),
            (":wq / ZZ", "Save and quit"),
            (":q!", "Quit without saving"),
            ("/pattern", "Search forward"),
            ("dd / yy / p", "Delete line / yank / paste"),
        ],
        related=["nano", "vi", "nvim", "emacs"],
        aliases=["vi", "nvim"],
        notes="vimtutor is the best way to learn. nvim is often aliased similarly.",
    ),
]


def write_detail(entry: dict) -> None:
    detail = {
        "name": entry["name"],
        "description": entry["description"],
        "synopsis": entry["synopsis"],
        "tags": entry["tags"],
        "examples": entry["examples"],
        "options": entry["options"],
        "related": entry["related"],
    }
    if entry.get("notes"):
        detail["notes"] = entry["notes"]
    if entry.get("distroNotes"):
        detail["distroNotes"] = entry["distroNotes"]
    if entry.get("distroVariants"):
        detail["distroVariants"] = entry["distroVariants"]

    path = CMD_DIR / f"{entry['name']}.json"
    path.write_text(json.dumps(detail, indent=2) + "\n", encoding="utf-8")


def write_index(entries: list[dict]) -> None:
    index = {
        "version": 1,
        "commands": [
            {
                "name": e["name"],
                "summary": e["summary"],
                "example": e.get("example"),
                "basic": bool(e.get("basic")),
                "tags": e["tags"],
                "detailFile": f"{e['name']}.json",
                "distros": e["distros"],
                "aliases": e["aliases"],
            }
            for e in entries
        ],
    }
    (DATA / "commands.json").write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    CMD_DIR.mkdir(parents=True, exist_ok=True)
    for old in CMD_DIR.glob("*.json"):
        old.unlink()

    names = [e["name"] for e in COMMANDS]
    if len(names) != len(set(names)):
        dupes = {n for n in names if names.count(n) > 1}
        raise SystemExit(f"Duplicate command names: {dupes}")

    entries = [enrich(dict(e)) for e in COMMANDS]
    for entry in entries:
        write_detail(entry)
    write_index(entries)

    basic_n = sum(1 for e in entries if e.get("basic"))
    package_n = sum(1 for e in entries if "package" in e.get("tags", []))
    print(f"Wrote {len(entries)} commands ({basic_n} basic, {package_n} package) to {CMD_DIR}")
    print(f"Index: {DATA / 'commands.json'}")


if __name__ == "__main__":
    main()
